version: '3.9'
services:
  postgres:
    image: quay.io/debezium/postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data:z
      - ./docker/postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:z

  clickhouse:
    image: clickhouse/clickhouse-server:23.11.5.29-alpine
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse:z
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

volumes:
  postgres_data:
  clickhouse_data:
