version: '3.9'
services:
  postgres:
    image: quay.io/debezium/postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data:z
      - ./docker/postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:z
  elasticsearch:
    image: elastic/elasticsearch:7.7.0
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - es_data_dir:/usr/share/elasticsearch/data:z

#  kibana:
#    image: elastic/kibana:7.7.0
#    ports:
#      - "5601:5601"

volumes:
  postgres_data:
  es_data_dir:
